/* Biblioteca Digital V12 — camada Ultimate: estoque, reposição, atividade, conquistas, autores e relatórios */
(function(){
  const get=(k,d)=>DB.get(k,d), set=(k,v)=>DB.set(k,v);
  DB.activity=()=>get('activity',[]); DB.saveActivity=v=>set('activity',v);
  DB.achievements=()=>get('achievements',[]); DB.saveAchievements=v=>set('achievements',v);
  DB.stockAlerts=()=>get('stockAlerts',{}); DB.saveStockAlerts=v=>set('stockAlerts',v);
  const track=(type,data={})=>{const u=session();if(!u)return;const a=DB.activity();a.unshift({id:uid('act'),userId:u.id,type,data,date:Date.now()});DB.saveActivity(a.slice(0,300));};
  const stock=(id)=>{const inv=DB.inventory();if(inv[id]===undefined){inv[id]=10;DB.saveInventory(inv)}return Number(inv[id]||0)};
  function ensureInventory(){const inv=DB.inventory();let changed=false;allBooks().forEach(b=>{if(inv[b.id]===undefined){inv[b.id]=10;changed=true}});if(changed)DB.saveInventory(inv)}
  ensureInventory();
  function applyOrderStock(){const applied=get('stockAppliedOrders',[]);const orders=DB.orders();const inv=DB.inventory();let changed=false;orders.forEach(o=>{if(applied.includes(o.id))return;(o.items||[]).forEach(i=>{const id=String(i.id);inv[id]=Math.max(0,Number(inv[id]??10)-Number(i.qty||0));});applied.push(o.id);changed=true});if(changed){DB.saveInventory(inv);set('stockAppliedOrders',applied)}}
  applyOrderStock();

  const oldAddCart=window.addCart;
  window.addCart=function(id){const b=bookById(id);if(!b)return;const s=stock(id);const qty=DB.cart().find(x=>String(x.id)===String(id))?.qty||0;if(s<=0)return toast('Livro esgotado. O administrador precisa reabastecer o estoque.');if(qty>=s)return toast(`Estoque disponível: ${s} unidade(s).`);track('cart',{bookId:id});return oldAddCart(id)};

  function stats(){const u=session(),orders=DB.orders().filter(o=>o.userId===u.id),lib=DB.library(),done=Object.values(lib).filter(x=>x.progress>=100).length;const pages=Object.values(lib).reduce((s,x)=>s+Math.round((x.progress||0)*3.2),0);return {orders:orders.length,spent:orders.reduce((s,o)=>s+Number(o.total||0),0),done,pages,views:DB.activity().filter(x=>x.userId===u.id&&x.type==='view').length}};
  function achievements(){const s=stats(),u=session(),reviews=DB.reviews().filter(r=>r.userId===u.id||r.user===u.name),w=DB.wishlist().length;const defs=[
    ['first','📖','Primeira leitura','Conclua seu primeiro livro',s.done>=1],['five','📚','Leitor iniciante','Conclua 5 livros',s.done>=5],['ten','🏆','Leitor dedicado','Conclua 10 livros',s.done>=10],['twenty','🔥','Maratonista','Conclua 20 livros',s.done>=20],['critic','⭐','Crítico','Faça 10 avaliações',reviews.length>=10],['wishlist','❤️','Curador','Guarde 10 livros na lista de desejos',w>=10],['buyer','🛍️','Colecionador','Faça seu primeiro pedido',s.orders>=1],['pages','📚','Explorador','Registre mais de 1.000 páginas',s.pages>=1000]
  ];return defs.map(x=>({...{id:x[0],icon:x[1],name:x[2],desc:x[3]},unlocked:x[4]}));}
  function activityPage(){const u=session(),a=DB.activity().filter(x=>x.userId===u.id).slice(0,50);return `<section class="section ultimate-page"><div class="section-head"><div><span class="badge">Minha jornada</span><h1>Minha atividade</h1><p>Seu histórico de leitura, compras e interações.</p></div></div><div class="ultimate-kpis"><div><b>${stats().done}</b><span>Livros concluídos</span></div><div><b>${stats().pages}</b><span>Páginas estimadas</span></div><div><b>${moneyBR(stats().spent)}</b><span>Total em pedidos</span></div><div><b>${stats().views}</b><span>Livros visitados</span></div></div><div class="panel"><h2>Atividade recente</h2>${a.map(x=>`<div class="activity-row"><span>${activityIcon(x.type)}</span><div><b>${activityText(x)}</b><small>${new Date(x.date).toLocaleString('pt-BR')}</small></div></div>`).join('')||'<div class="empty"><strong>Nenhuma atividade ainda</strong>Comece explorando o catálogo.</div>'}</div></section>`}
  function activityIcon(t){return ({view:'👀',cart:'🛒',read:'📖',review:'⭐',wishlist:'❤️',order:'📦'})[t]||'•'}
  function activityText(x){const b=x.data?.bookId?bookById(x.data.bookId):null;return ({view:`Você visualizou ${b?esc(b.titulo):'um livro'}`,cart:`Você adicionou ${b?esc(b.titulo):'um livro'} ao carrinho`,read:`Você atualizou sua leitura de ${b?esc(b.titulo):'um livro'}`,review:'Você publicou uma avaliação',wishlist:'Você atualizou sua lista de desejos',order:'Você realizou um pedido'}[x.type]||'Você realizou uma ação na biblioteca')}
  function achievementsPage(){const list=achievements();return `<section class="section ultimate-page"><div class="section-head"><div><span class="badge">Gamificação</span><h1>Conquistas</h1><p>Transforme sua rotina de leitura em metas.</p></div></div><div class="achievement-grid">${list.map(a=>`<div class="achievement ${a.unlocked?'unlocked':''}"><span>${a.icon}</span><div><b>${a.name}</b><p>${a.desc}</p><small>${a.unlocked?'✓ Conquistada':'🔒 Bloqueada'}</small></div></div>`).join('')}</div></section>`}
  function authorsPage(){const map={};allBooks().forEach(b=>{map[b.autor]??=[];map[b.autor].push(b)});const authors=Object.entries(map).sort((a,b)=>a[0].localeCompare(b[0],'pt'));return `<section class="section ultimate-page"><div class="section-head"><div><span class="badge">Autores</span><h1>Explore por autor</h1><p>${authors.length} autores encontrados no catálogo.</p></div></div><div class="author-grid">${authors.map(([name,books])=>`<button class="author-card" data-author="${esc(name)}"><span>${esc(initials(name))}</span><div><b>${esc(name)}</b><small>${books.length} livro(s) · ${esc([...new Set(books.map(b=>b.genero))].slice(0,2).join(' · '))}</small></div></button>`).join('')}</div></section>`}
  function reportsPage(){if(session().role!=='admin')return `<section class="section"><div class="empty"><strong>Acesso restrito</strong>Somente administradores.</div></section>`;const orders=DB.orders(),inv=DB.inventory(),books=allBooks();const revenue=orders.reduce((s,o)=>s+Number(o.total||0),0);const low=books.filter(b=>stock(b.id)<=5);const top={};orders.forEach(o=>(o.items||[]).forEach(i=>top[i.id]=(top[i.id]||0)+i.qty));const best=Object.entries(top).sort((a,b)=>b[1]-a[1]).slice(0,8);return `<section class="section ultimate-page"><div class="section-head"><div><span class="badge">Administração</span><h1>Relatórios</h1><p>Visão geral do desempenho da biblioteca.</p></div></div><div class="ultimate-kpis"><div><b>${moneyBR(revenue)}</b><span>Receita local</span></div><div><b>${orders.length}</b><span>Pedidos</span></div><div><b>${books.length}</b><span>Livros</span></div><div><b>${low.length}</b><span>Estoque baixo</span></div></div><div class="report-grid"><div class="panel"><h2>Mais vendidos</h2>${best.map(([id,q])=>{const b=bookById(id);return b?`<div class="report-row"><span>${esc(b.titulo)}</span><b>${q} un.</b></div>`:''}).join('')||'<p class="muted">Ainda não há vendas.</p>'}</div><div class="panel"><h2>Estoque baixo</h2>${low.map(b=>`<div class="report-row"><span>${esc(b.titulo)}</span><b class="stock-danger">${stock(b.id)} un.</b></div>`).join('')||'<p class="muted">Nenhum livro com estoque baixo.</p>'}</div></div></section>`}

  function restockModal(id){const b=bookById(id);if(!b)return;const current=stock(id);$('#modalContent').innerHTML=`<h2>Reabastecer estoque</h2><p class="muted">${esc(b.titulo)}</p><div class="stock-modal-current">Estoque atual <strong>${current}</strong></div><form id="restockForm"><div class="form-grid"><div class="field"><label>Quantidade a adicionar</label><input name="qty" type="number" min="1" max="9999" value="10" required></div><div class="field"><label>Novo estoque total (opcional)</label><input name="set" type="number" min="0" max="99999" placeholder="Ex.: 50"></div></div><div class="field"><label>Motivo</label><select name="reason"><option>Reposição de estoque</option><option>Nova remessa</option><option>Correção de inventário</option><option>Entrada promocional</option></select></div><button class="btn btn-primary">Confirmar reposição</button></form>`;$('#modal').classList.remove('hidden');$('#restockForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),inv=DB.inventory();const explicit=String(f.get('set')||'').trim();inv[id]=explicit!==''?Number(explicit):current+Number(f.get('qty')||0);DB.saveInventory(inv);const logs=get('stockLogs',[]);logs.unshift({id:uid('stock'),bookId:id,old:current,new:inv[id],qty:Number(f.get('qty')||0),reason:f.get('reason'),date:Date.now(),adminId:session().id});set('stockLogs',logs.slice(0,200));$('#modal').classList.add('hidden');toast(`Estoque de “${b.titulo}” atualizado para ${inv[id]}.`);renderPage('admin')};}

  function adminUltimate(){if(session().role!=='admin')return `<section class="section"><div class="empty"><strong>Acesso restrito</strong>Somente administradores.</div></section>`;const users=DB.users(),orders=DB.orders(),books=allBooks(),low=books.filter(b=>stock(b.id)<=5);return `<section class="section ultimate-admin"><div class="section-head"><div><span class="badge">Painel administrativo</span><h1>Administração</h1><p>Gerencie catálogo, estoque, pedidos, usuários e indicadores.</p></div><button class="btn btn-primary" data-admin-tab="inventory">📦 Estoque</button></div><div class="ultimate-kpis"><div><b>${users.length}</b><span>Usuários</span></div><div><b>${books.length}</b><span>Livros</span></div><div><b>${orders.length}</b><span>Pedidos</span></div><div><b>${low.length}</b><span>Estoque baixo</span></div></div><div class="admin-tabs-ultimate"><button class="btn btn-primary" data-admin-tab="inventory">📦 Estoque</button><button class="btn" data-admin-tab="catalog">📚 Catálogo</button><button class="btn" data-admin-tab="users">👥 Usuários</button><button class="btn" data-admin-tab="orders">🛒 Pedidos</button><button class="btn" data-admin-tab="coupons">🎟️ Cupons</button><button class="btn" data-page-link="relatorios">📊 Relatórios</button></div><div id="ultimateAdminPanel">${inventoryPanel()}</div></section>`}
  function inventoryPanel(){const books=allBooks();return `<div class="panel"><div class="section-head"><div><h2>Controle de estoque</h2><p>Reabasteça livros quando acabarem ou defina um novo estoque total.</p></div></div><div class="inventory-list">${books.map(b=>`<div class="inventory-row"><div class="inventory-cover">${coverImage(b,'inventory-img')}</div><div class="inventory-main"><b>${esc(b.titulo)}</b><small>${esc(b.autor)} · ${esc(b.genero)}</small></div><div class="inventory-number ${stock(b.id)<=5?'low':''}"><strong>${stock(b.id)}</strong><small>disponíveis</small></div><div class="inventory-actions"><button class="btn btn-primary" data-restock="${b.id}">+ Reabastecer</button><button class="btn" data-stock-set="${b.id}">Definir estoque</button></div></div>`).join('')}</div></div>`}
  function catalogPanel(){return `<div class="panel"><div class="section-head"><div><h2>Catálogo e estoque</h2><p>Cadastre novos títulos e controle a disponibilidade.</p></div></div><form id="bookFormUltimate" class="toolbar"><input name="titulo" required placeholder="Título"><input name="autor" required placeholder="Autor"><input name="genero" required placeholder="Gênero"><input name="ano" type="number" required placeholder="Ano"><input name="preco" type="number" step="0.01" required placeholder="Preço"><input name="estoque" type="number" min="0" value="10" placeholder="Estoque"><input name="capa" placeholder="URL da capa (opcional)"><button class="btn btn-primary">Adicionar livro</button></form><div class="table-wrap"><table class="table"><thead><tr><th>Livro</th><th>Preço</th><th>Estoque</th><th>Ações</th></tr></thead><tbody>${DB.customBooks().map(b=>`<tr><td>${esc(b.titulo)}</td><td>${moneyBR(price(b))}</td><td>${stock(b.id)}</td><td><button class="btn" data-restock="${b.id}">Repor</button> <button class="btn btn-danger" data-book-delete="${b.id}">Excluir</button></td></tr>`).join('')||'<tr><td colspan="4">Nenhum livro personalizado.</td></tr>'}</tbody></table></div></div>`}
  function usersPanel(){return `<div class="panel"><h2>Usuários</h2><div class="table-wrap"><table class="table"><thead><tr><th>Nome</th><th>Usuário</th><th>Perfil</th><th>Status</th><th>Ações</th></tr></thead><tbody>${DB.users().map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.username)}</td><td>${u.role==='admin'?'Administrador':'Leitor'}</td><td>${u.active?'<span class="badge">Ativo</span>':'<span class="badge danger-badge">Bloqueado</span>'}</td><td>${u.id!=='admin-1'?`<button class="btn" data-user-toggle="${u.id}">${u.active?'Bloquear':'Ativar'}</button> <button class="btn btn-danger" data-user-delete="${u.id}">Excluir</button>`:'Conta principal'}</td></tr>`).join('')}</tbody></table></div></div>`}
  function ordersPanel(){return `<div class="panel"><h2>Pedidos</h2><div class="table-wrap"><table class="table"><thead><tr><th>Pedido</th><th>Cliente</th><th>Data</th><th>Pagamento</th><th>Total</th><th>Status</th></tr></thead><tbody>${DB.orders().map(o=>{const u=DB.users().find(x=>x.id===o.userId);return `<tr><td>#${o.id.slice(-6)}</td><td>${esc(u?.name||'Usuário')}</td><td>${new Date(o.date).toLocaleDateString('pt-BR')}</td><td>${esc(o.paymentLabel||o.payment||'—')}</td><td>${moneyBR(o.total)}</td><td><span class="badge">${esc(o.status||'Pedido recebido')}</span></td></tr>`}).join('')||'<tr><td colspan="6">Nenhum pedido.</td></tr>'}</tbody></table></div></div>`}
  function couponsPanel(){const cs=DB.coupons();return `<div class="panel"><h2>Cupons</h2><form id="couponUltimate" class="toolbar"><input name="code" required placeholder="CODIGO"><select name="type"><option value="percent">Percentual</option><option value="fixed">Valor fixo</option></select><input name="value" type="number" min="1" step="0.01" required placeholder="Valor"><button class="btn btn-primary">Criar cupom</button></form><div class="table-wrap"><table class="table"><tbody>${cs.map(c=>`<tr><td><b>${esc(c.code)}</b></td><td>${c.type==='percent'?c.value+'%':moneyBR(c.value)}</td><td>${c.active?'Ativo':'Inativo'}</td><td><button class="btn" data-coupon-toggle="${esc(c.code)}">${c.active?'Desativar':'Ativar'}</button></td></tr>`).join('')}</tbody></table></div></div>`}
  function bindUltimateAdmin(){const p=$('#ultimateAdminPanel');$$('[data-admin-tab]').forEach(b=>b.onclick=()=>{const t=b.dataset.adminTab;p.innerHTML=t==='inventory'?inventoryPanel():t==='catalog'?catalogPanel():t==='users'?usersPanel():t==='orders'?ordersPanel():t==='coupons'?couponsPanel():inventoryPanel();bindUltimateAdmin();});$$('[data-restock]').forEach(b=>b.onclick=()=>restockModal(b.dataset.restock));$$('[data-stock-set]').forEach(b=>b.onclick=()=>restockModal(b.dataset.stockSet));$$('[data-user-toggle]').forEach(b=>b.onclick=()=>{const us=DB.users(),i=us.findIndex(x=>x.id===b.dataset.userToggle);if(i<0)return;us[i].active=!us[i].active;DB.saveUsers(us);adminRefresh();toast(us[i].active?'Conta ativada':'Conta bloqueada')});$$('[data-user-delete]').forEach(b=>b.onclick=()=>{if(confirm('Excluir esta conta?')){DB.saveUsers(DB.users().filter(x=>x.id!==b.dataset.userDelete));adminRefresh();toast('Conta excluída')}});$$('[data-book-delete]').forEach(b=>b.onclick=()=>{if(confirm('Excluir este livro do catálogo?')){DB.saveCustomBooks(DB.customBooks().filter(x=>String(x.id)!==String(b.dataset.bookDelete)));adminRefresh();toast('Livro removido')}});$$('[data-coupon-toggle]').forEach(b=>b.onclick=()=>{const cs=DB.coupons(),c=cs.find(x=>x.code===b.dataset.couponToggle);if(c)c.active=!c.active;DB.saveCoupons(cs);adminRefresh()});$('#bookFormUltimate')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),b={id:uid('book'),titulo:f.get('titulo').trim(),autor:f.get('autor').trim(),genero:f.get('genero').trim(),ano:+f.get('ano'),avaliacao:5,preco:+f.get('preco'),capa:f.get('capa').trim(),descricao:'Livro adicionado pelo administrador.'};const c=DB.customBooks();c.push(b);DB.saveCustomBooks(c);const inv=DB.inventory();inv[b.id]=Math.max(0,+f.get('estoque')||0);DB.saveInventory(inv);adminRefresh();toast('Livro adicionado')});$('#couponUltimate')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),cs=DB.coupons(),code=f.get('code').trim().toUpperCase();if(cs.some(c=>c.code===code))return toast('Cupom já existe.');cs.push({code,type:f.get('type'),value:Number(f.get('value')),active:true});DB.saveCoupons(cs);adminRefresh();toast('Cupom criado')})}
  function adminRefresh(){renderPage('admin')}

  const baseRender=window.renderPage;
  window.renderPage=function(page){if(page==='admin'||page==='atividade'||page==='conquistas'||page==='autores'||page==='relatorios'){state.page=page;$$('.nav').forEach(b=>b.classList.toggle('active',b.dataset.page===page));$('#crumb').innerHTML=`Biblioteca / <b>${esc(pages[page]||page)}</b>`;if(page==='admin'){$('#content').innerHTML=adminUltimate();bindUltimateAdmin();}else{$('#content').innerHTML=page==='atividade'?activityPage():page==='conquistas'?achievementsPage():page==='autores'?authorsPage():reportsPage();bindUltimateContent();}window.scrollTo({top:0,behavior:'smooth'});return;}baseRender(page);};
  pages.atividade='Minha atividade';pages.conquistas='Conquistas';pages.autores='Autores';pages.relatorios='Relatórios';
  function bindUltimateContent(){
    $$('[data-page-link]').forEach(b=>b.onclick=()=>renderPage(b.dataset.pageLink));
    $$('[data-author]').forEach(b=>b.onclick=()=>{state.query=b.dataset.author;state.pageNum=1;renderPage('catalogo');});
  }
  const nav=document.querySelector('.sidebar nav');if(nav&&!nav.querySelector('[data-page="atividade"]'))nav.insertAdjacentHTML('beforeend','<label>Mais</label><button class="nav" data-page="atividade">◔ <span>Minha atividade</span></button><button class="nav" data-page="conquistas">🏆 <span>Conquistas</span></button><button class="nav" data-page="autores">✎ <span>Autores</span></button>');
  nav?.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>renderPage(b.dataset.page));
  const oldOpen=window.openBook;window.openBook=function(id){track('view',{bookId:id});oldOpen(id)};
  const oldReader=window.reader;window.reader=function(id){track('read',{bookId:id});oldReader(id)};
  // Enriquecer o footer com atalhos adicionais.
  document.querySelector('.footer-links')?.insertAdjacentHTML('beforeend','<div><b>Descobrir</b><button data-page-link="atividade">Minha atividade</button><button data-page-link="conquistas">Conquistas</button><button data-page-link="autores">Autores</button></div>');
  document.querySelectorAll('.footer-links [data-page-link]').forEach(b=>b.onclick=()=>renderPage(b.dataset.pageLink));
  if(session())refreshChrome();
})();
